Refactor/image optimization
prgrms-web-devcourse/Team-PODO-ODEEGO-FE pull request #103
Opened 2023-03-11 12:41 UTC by Kal-MH

## 이슈번호
close #89 #102
## 1. 작업내용
![searchMidPoint](https://user-images.githubusercontent.com/59648372/224483753-c9bdecab-41ce-4516-8c1b-4308871d4973.gif)

- 주변장소 추천 무한 스크롤을 적용합니다.
  1. useInfiniteQuery를 사용했습니다.
  2. 현재 로딩컴포넌트를 확인하기 위해 임의로 0.5초 지연을 두었습니다.
  3. 마지막 요소까지 모두 불러오게 되면 서비스 로고를 보여주도록 하였습니다.
  4. lazy loading을 적용했습니다.

## 2. 작업 하면서 겪은 이슈

1. 이미지를 로딩할 때, 에러가 다수 발생합니다.
![화면 캡처 2023-03-08 193302](https://user-images.githubusercontent.com/59648372/224351987-206a7d83-6e18-4fc6-b73a-6294cef47c77.png)
2. 이미지 소스가 2.5MB, 1.2MB로 용량이 큰 것도 있어서 불러오는 속도가 느립니다.
3. next/images loader옵션을 사용하고 있는데 다음의 warning 메세지가 생겼습니다.
![화면 캡처 2023-03-10 024152](https://user-images.githubusercontent.com/59648372/224352523-e4de948c-7a14-49cc-bccb-cf3a0e25d352.png)
 - url을 조작해서 width를 줘보려고 했지만, 이미지 원소스 자체에서 다양한 사이즈를 제공하지 않는 것도 있는 거 같습니다.(오히려 404에러가 다수 발생해서 width옵션을 줄 수 없었습니다)

## 3. PR 포인트

1. 이미지 로딩 시 발생하는 에러는 다음 2가지로 대처했습니다.
  - onError이벤트로 DOM요소 삭제하기
  - http프로토콜 filter로 걸러내기.
        -  NET: ERR_CERT_INVALID_NAME 에러가 모두  http 프로토콜로 되어 있는 url의 경우에 발생했기 때문에 filter를 통해 걸러주었습니다. 하지만, 임시방편 대처라는 생각이 들어서 더 좋은 해결방법이 있을 지 궁금합니다.
2. next/images의 Image컴포넌트를 일단 걷어냈습니다.
   - 이미지 소스 자체가 2.5MB처럼 용량이 큰 것들이 있어서 next/images의 IMAGE컴포넌트를 사용하면 좋을 것이라고 생각 loader를 props로 주어 처리하려고 했는데요.  3번 이슈와 같은 warning메세지가 발생했고, resize를 통해 width를 주거나, upoptimized 옵션을 줘야 한다고 공식문서에서 확인할 수 있었습니다. 
   - resize의 경우 3번에서 명시한 이유로 좋은결과를 얻지 못했고, upoptimized의 경우, 이럴거면 Image컴포넌트를 쓰는 이유가 없지 않을까 생각하게 되었습니다.
   - 혹시, Image컴포넌트를 쓰면서 3번의 warning메세지를 해결할 수 있는 방법은 없을까요?
3. 현재 상황에서 용량이 큰 이미지를 어떻게 처리하면 좋을까요...

2023-03-12 16:15 UTC, fly1chop requested changes
수고하셨습니다~ 
리뷰 남겼으니 확인 부탁드립니다~

2023-03-12 16:15 UTC, fly1chop commented on src/components/place/place-image.tsx
> +`;
이미지가 3개만 있어도 margin-right 때문에 스크롤바가 보이는것 같습니다. 그래서 `Image`에 마진을 빼고 아래 /components/place/place.tsx 파일에 있는 `ImageContainer`에서 `gap: 0.6rem`을 주면 될것같습니다.

그리고 `Container`에서 이미 `border-radius`와 `overflow: hidden`하고 있어서 아래 와 같이 수정하면 좋을 것 같습니다.

```javascript
const Container = styled.div`
  flex: 0 0 auto;
  aspect-ratio: 1/1;
  overflow: hidden;
  border-radius: 1rem;
`;

const Image = styled.img`
  width: 12.4rem;
  height: 12.4rem;
  object-fit: cover;

  &.disabled {
    display: none;
  }
`;

// place.tsx 안에 있는 컴포넌트
const ImageContainer = styled.div`
  width: 100%;
  display: flex;
  padding-bottom: 0.5rem;
  overflow-x: auto;
  gap: 0.6rem;
`;
```

PS. `object-fit: cover`로 지금 이미지 찌끔 찌그러져있는거 고칠 수 있을것같습니다~

2023-03-12 16:15 UTC, fly1chop commented on src/components/place/place.tsx
> +    toast.success("복사 완료", {
오! 저도 이 방법으로 해야겠네요 ^^b

2023-03-12 16:15 UTC, fly1chop commented on src/components/place/place.tsx
> +          <IconButton sx={{ padding: 0 }} onClick={handleClickShareClipboard}>
padding: 0이라서 그런지 버튼 허버 효과가 잘 보이지 않습니다. 따라서 아래와 같이 수정하는건 어떤가요?
```javascript
<IconButton
  sx={{ padding: "0.5rem" }}
  onClick={handleClickShareClipboard}>
  <IosShareIcon
    sx={{
      display: "block",
      height: "2rem",
      width: "2rem",
      color: "#5ab27d",
    }}
  />
</IconButton>
```

2023-03-13 04:21 UTC, Kal-MH commented on src/components/place/place.tsx
> +          <IconButton sx={{ padding: 0 }} onClick={handleClickShareClipboard}>
오, 이 부분 수정해서 커밋을 올렸는데 혹시 반영이 안되었나요?

2023-03-13 04:22 UTC, Kal-MH commented on src/components/place/place.tsx
> +          <IconButton sx={{ padding: 0 }} onClick={handleClickShareClipboard}>
안 되었군요...

2023-03-13 06:22 UTC, fly1chop approved these changes
LGTM!

2023-03-13 06:22 UTC, merged