Design/places list page
prgrms-web-devcourse/Team-PODO-ODEEGO-FE pull request #21
Opened 2023-02-22 10:17 UTC by Kal-MH

## 이슈번호
[#16]
 
## 1. 작업내용
- 주변 장소 보여주는 페이지 리스트 디자인 작업
![화면 캡처 2023-02-22 191445](https://user-images.githubusercontent.com/59648372/220590466-bdf122b6-8138-4ec0-934a-d2e8e447130d.png)
## 2. 작업 하면서 겪은 이슈
- 현재 백엔드 api에는 이미지가 포함되어 있지 않습니다. 이미지 컴포넌트는 언제든지 빠질 수 있습니다. 
## 3. PR 포인트
- 디자인만 들어간 구현입니다.
- `/places` url을 통해서 접근할 수 있습니다(임시로 지정된 url로 이후에 바뀔 수 있습니다)
- 컨테이너에, 컨테이너 투성이인데, css 리팩토링 리뷰도 언제든 환영이에요~~:)b
- 작업 develop브랜치가 계속 바뀌기 때문에 머지 전에 항상 싱크를 맞춰서 진행하겠습니다

2023-02-22 13:11 UTC, fly1chop requested changes
미현님~ 너무 수고 많으셨습니다!! 이미지 border-radius를 추가했으며, 리뷰코드 확인해주세요~

2023-02-22 13:11 UTC, fly1chop commented on src/components/places/place.tsx
> +      </ImageContainer>
이미지 border-radius를 주기 위해 `div`로 감싸기 
```suggestion
        {tmpImageList.map((i, index) => (
          <div key={index}>
          <Image
            src={`/cafe${(i % 3) + 1}.png`}
            alt='cafe image'
            width={125}
            height={125}
            priority
          />
          </div>
        ))}
      </ImageContainer>
```

2023-02-22 13:11 UTC, fly1chop commented on src/components/places/place.tsx
> +`;
```suggestion
const ImageContainer = styled.div`
  width: 100%;
  display: flex;
  gap: 1rem;

  overflow-x: auto;
  white-space: nowrap;

  padding-bottom: 0.3rem;

  &::-webkit-scrollbar {
    height: 0.25rem;
  }

  &::-webkit-scrollbar-thumb {
    background-color: ${COLORS.mainOrange};
    border-radius: 1rem;
  }

  > div {
    flex: 0 0 auto;
    aspect-ratio: 1/1;
    overflow: hidden;
    border-radius: 1rem;
  }
`;
```

2023-02-22 13:17 UTC, Kal-MH commented on src/components/places/place.tsx
> +`;
오호, 요런 방법이 있군요:)!
그러네요, 사진이 이미 깎아져 있어서 제가 border-radius 준 마냥 생각하고 있었네요ㅎ

2023-02-24 04:50 UTC, fly1chop approved these changes
LGTM

2023-02-25 10:42 UTC, merged