Feature/meeting form
prgrms-web-devcourse/Team-PODO-ODEEGO-FE pull request #34
Opened 2023-02-27 12:26 UTC by fly1chop

## 이슈번호
 #28 
## 1. 작업내용
- server-side로 모임 상세 정보 받아 페이지 props 전달
- 모임 인원수 만큼 `FormInput` 만들기
- 모임 취소 버튼
- 중간지점 찾기 버튼
- `header` 및 `main` 컴포넌트 스타일링 수정
- 로고 svg 파일로 변경

## 2. 작업 하면서 겪은 이슈
- 
## 3. PR 포인트
- `group/[groupId]` 파일을 확인하시면 됩니다

2023-02-27 19:52 UTC, Kal-MH requested changes
지원님:) 수고 많으셨습니다bb

state가 여러 개가 추가되니 정신이 하나도 없네요. 우선은 기능 구현에 집중하고, 후반부에 고도화를 할 수 있었으면 좋겠습니다!
코멘트 한 번 읽어주세요:)

그리고, search페이지에서 검색 결과 리스트가 안 보이던데, 임시로 막아두신건가요?

2023-02-27 19:52 UTC, Kal-MH commented on src/components/home/address-form.tsx
> +          stationName: a.stationName,
P3. 중간지점 찾는 API 명세를 확인해주세요

아무래도, 모임 상세 API를 참고하신 거 같은데, 맞나요:)? address-form이 다른데 사용되는 게 아니라면 현재 여기서는 중간지점 찾기 API가 호출됩니다. 여기서는 stationName이 아니라, name을 받습니다!

2023-02-27 19:52 UTC, Kal-MH commented on src/components/home/address-form.tsx
> +        <Stack spacing={1.5}>
Stack을 사용하니까 편하군요!

2023-02-27 19:52 UTC, Kal-MH commented on src/components/layout/header.tsx
> +        src='/LOGO.svg'
저도 안 지 얼마 안됐습니다만, 좀 더 빨리 알려드릴걸 그랬네요..
nextjs에서 image컴포넌트를 사용할 때, production모드에서는 Uppercase가 잘 안읽혀진다고 하네요.

혹시 lowercase로 바꿔주실 수 있을까요:)?

2023-02-27 19:52 UTC, Kal-MH commented on src/pages/group/[groupId].tsx
> +}: InferGetServerSidePropsType<typeof getServerSideProps>) => {
오, 드디어 SSR 등장이군요:)b

2023-02-27 19:52 UTC, Kal-MH commented on src/pages/group/[groupId].tsx
> +  console.log(capacity, remainingTime, participants, owner);
console.log 하하핫

2023-02-28 07:47 UTC, fly1chop commented on src/components/home/address-form.tsx
> +          stationName: a.stationName,
중간지점 찾기 API에 해당 속성을 `stationName`으로 변경했습니다 :)

2023-02-28 07:48 UTC, fly1chop commented on src/components/layout/header.tsx
> +        src='/LOGO.svg'
오홍 그렇군요! 감사합니다 ^^

2023-02-28 08:06 UTC, fly1chop commented
@Kal-MH 
리뷰 반영 했습니다~
그리고 `name`이라는 타입을 모두 `stationName`으로 통일시켜서 전체적으로 타입 수정했습니다. 혹시라도 빠진게 있으면 말씀해주세요~

2023-02-28 12:25 UTC, closed without merging