Jaekwan ahn feature/search link2
prgrms-web-devcourse/Team-PODO-ODEEGO-FE pull request #51
Opened 2023-03-01 14:00 UTC by jaekwanAHN

## 이슈번호
 #31 
## 1. 작업내용
- 공유된 링크로 접속시 화면을 구성합니다.
## 2. 작업 하면서 겪은 이슈
- 검색어에 '역'이 들어가지 않아도 검색이 되게 끔 하는 과정에서 검색결과가 없는경우를 따로 분리하는 과정이 오래걸렸음. 현재도 '검색 결과가 없습니다' 라는 메시지가 출력되지 않고 아이콘만 등장하는 상황이 있는데 수정예정.

## 3. PR 포인트
- 로그인 유무에 따른 모달. 로그인 유무는 recoil를 사용하여 token의 유무로 판별합니다.
![image](https://user-images.githubusercontent.com/12118892/221810826-164c5e53-623e-4acb-a854-d98edc9e413e.png)
- 아직 유저 닉네임을 받아오지 않기 때문에 000 이라고 임시 표기됩니다.
![image](https://user-images.githubusercontent.com/12118892/221811138-789d3eb9-682e-4006-9ab1-de2fd1768f17.png)
- 검색어 후보중 1개를 선택하면 다음과 같은 모달이 생성됩니다.
장소를 확정하면 recoil에 해당 내용이 기록됩니다. (기존 로직과 동일한데 추후에 수정해야 될지도 모릅니다.)
아직 BE API가 배포되어 있지 않기 때문에 404 에러가 발생합니다.
내 장소 입력하기의 경우 '내정보'를 받아오는 BE API가 없기 때문에 지정된 동작이 없습니다.
![image](https://user-images.githubusercontent.com/12118892/221811289-328ebfdb-8036-4e84-99b3-6ae0b61c05a2.png)

2023-03-03 06:26 UTC, Kal-MH requested changes
재관님! 수고 많으셨습니다:)

제안 드렸는데, 선뜻 응해주셔서 감사합니다. 
window error만 바로 확인해보시면 좋을 거 같습니다.

PR에 남겨주신 input value error에 대한 부분은 제 환경에서는 발생하지 않아서 코멘트를 남기지 않았습니다~

2023-03-03 06:26 UTC, Kal-MH commented on src/components/search/search-input.tsx
> +  window.addEventListener("popstate", () => {
p3. 제가 돌렸을 때, `window is not defined`이라는 에러가 떴는데, 확인 한 번 해주시면 좋을 거 같아요!

(nextjs에서 초기 렌더링할 때는, window나 document객체가 선언되지 않아서 참조할 수 없다고 합니다.)

2023-03-03 06:26 UTC, Kal-MH commented on src/components/search/search-input.tsx
> +    }
p5. 여기다가 window 이벤트 리스너를 넣을까요? useEffect는 컴포넌트 렌더링이 완료된다고 실행된다고 알고 있습니다.

2023-03-03 06:26 UTC, Kal-MH commented on src/components/search/search-input.tsx
> +          // 주소 입력 후 메인 화면으로 redirection
Ask.
링크를 공유 받은 사람은 주소 입력 후, redirection이 아닌, "출발지를 이미 입력하셨습니다"와 같은 문구를 보여주고
유효 만료된 페이지를 본다고 알고 있었는데 바뀌었나요:)?

2023-03-03 06:26 UTC, Kal-MH commented on src/components/search/search-input.tsx
> +    openModal({
Ask.
비회원으로 메인에서 바로 주소 검색을 할 때도, 동일하게 모달창이 뜨는 것 같더라구요.
이 경우에는 주소지 검색이 자유롭게 수정이 가능해서, '출발지를 확정합니다'와 같은 모달창이 뜨는 것이 맞을까 하는 생각이 들었습니다.

2023-03-03 06:26 UTC, Kal-MH commented on src/components/search/search-input.tsx
> +    }
p5. groupID가 있으면 무조건 `OOO님이 주소를 요청했습니다'라는 모달이 뜰 수 있을 거 같은데, 잘 이해했을까요?

host의 경우도 groupID가 있으면 동일하게 모달을 볼 수 있을 거 같은데, 어떻게 생각하시나요?
(사실 url이 정확히 어떻게 연결되는지 잘 몰라서 계획하고 계신 동작과 상관 없는 의견이라면 그냥 넘어가시면 될 듯합니다 ㅎㅎ)

2023-03-03 15:04 UTC, Seung-hwan285 approved these changes
재관님 슬랙 지금봤네요 ㅋㅋㅋ 리뷰 간단하게 남겨보았습니다.

2023-03-03 15:04 UTC, ghost commented on src/components/search/search-input.tsx
> +  }
p3: 중첩 if문 피해주세요!
뎁스가 깊어지면 가독성이 안좋아질거같아요 차라리  논리 연산자 사용해서 분기처리해도 될 듯 싶습니다~

2023-03-03 15:04 UTC, ghost commented on src/components/search/search-input.tsx
>      }
p4: refetchOnMount default 값이 true로 알고있는데 안넣어도 될 것 같습니다.
default 가 true이면 페이지 최초방문시 데이터 캐싱하고 이후 재방문시 컴포넌트가 마운트 되고 이때 캐시가 있으면 사용하고
이후 캐시가 stale 상태라면 refech 한다는 의미로 알고 있는데 맞을까요 ?.?

그리고 false, alway일때도  페이지 최초방문하고 데이터캐싱 -> 이후 재방문시 컴포넌트 마운트 -> 캐시있으면 사용하는거까지는 전부 같은걸로 알고 있는데 여기서 default값인 true 값을  지정하신 이유가 있을까요

2023-03-03 15:04 UTC, ghost commented on src/components/search/search-input.tsx
>                return (
👍

2023-03-03 15:04 UTC, ghost commented on src/pages/api/search.ts
> +
p5: type에 넣어서 따로 사용해도 좋을 것 같습니다~

2023-03-04 10:25 UTC, jaekwanAHN commented on src/components/search/search-input.tsx
> +          // 주소 입력 후 메인 화면으로 redirection
아직 만료 페이지나 중복 submit에 대한 응답을 어떻게 받아오는지 못정해서 임시로 해두었습니다!

2023-03-04 10:27 UTC, jaekwanAHN commented on src/components/search/search-input.tsx
> +    openModal({
아 그렇군요. 그 부분에 대해서 놓친것같습니다.

회원/비회원을 토큰으로 구별하니까 토큰의 유무에 따라서 다른 UI(모달)를 보여주면 괜찮을까요?

2023-03-04 10:32 UTC, jaekwanAHN commented on src/components/search/search-input.tsx
>      }
캐시 stale에 대해서는 저도 그렇게 알고있어요!
refetchOnMount의 default value에 대해서는 제가 제대로 모르고있었네요!

2023-03-04 10:33 UTC, jaekwanAHN commented on src/pages/api/search.ts
> +
이 부분은 api 함수들 고치면서 적용하겠습니다!
지금 api사용하는 방식에서는 환경변수가 노출되는 문제가 있어서 고치려고 합니다!

2023-03-04 10:42 UTC, jaekwanAHN commented on src/components/search/search-input.tsx
> +    }
host인 경우 확인 모달이 뜨지 않도록 수정했습니다.

2023-03-04 10:42 UTC, jaekwanAHN commented on src/components/search/search-input.tsx
> +  window.addEventListener("popstate", () => {
아래쪽에 useEffect안으로 변경했어요!
 처음에 해당 코드를 작성 할때는 잘 동작해서 이상하다고 생각했었는데 역시나 에러가 나는군요.

2023-03-04 11:28 UTC, Kal-MH approved these changes
수고하셨습니다

2023-03-04 11:57 UTC, merged