Design/home address form
prgrms-web-devcourse/Team-PODO-ODEEGO-FE pull request #9
Opened 2023-02-20 14:59 UTC by Kal-MH

## 이슈번호

[#7 ]
 
## 1. 작업내용
- 주소 입력창 레이아웃 구현
![화면 캡처 2023-02-20 190536](https://user-images.githubusercontent.com/59648372/220138962-e44b389e-5271-445c-a5e9-d737d6b2db60.png)

## 2. 작업 하면서 겪은 이슈
- normalize css가 2개 생성되어 있어서 하나는 삭제했고, 기존과 다른 부분을 약간 수정했습니다.

## 3. PR 포인트
- 기본 전체 레이아웃을 잡아놨습니다. 이 부분에 있어서 이슈가 발생한다면 추후 논의해봐도 좋을 것 같습니다 
    - components/layout 폴더를 참조하면 됩니다.
- 기능이 들어가 있지 않고 레이아웃만 구현된 코드를 올립니다.
- components/home-address 폴더와 pages/index.tsx를 봐주시면 될 거 같습니다.

2023-02-20 19:02 UTC, fly1chop requested changes
미현님~ 수고 많으셨습니다~ 리뷰 남긴거 확인하시고 문의사항 있으시면 말해주세요~~

PS. 혹시 본 기능에선 react-hook-form을 활용할 방법이 있을까요? 저도 같이 고민해보겠습니다~

2023-02-20 19:02 UTC, fly1chop commented on src/components/home-address/Header.tsx
> +  background-color: ${({ colors }) => colors.backgroundAccent};
'colors'를 prop으로 받아쓰는 방법보다 바로 'COLORS' 변수를 가져다 사용할 수 있을것같아요!
```suggestion
  background-color: ${COLORS.backgroundAccent};
```

2023-02-20 19:02 UTC, fly1chop commented on src/components/home-address/Main.tsx
> +const MAIN_TEXT = "만날 사람 주소를 추가해주세요";
이런 문구 관련 const를 constants 폴더에 넣기 시작하셔도 될것같아요 :)

2023-02-20 19:02 UTC, fly1chop commented on src/components/home-address/address-form.tsx
> +          <IconButton aria-label='add' sx={{ color: "#b4c9bc" }}>
Wow~ aria-label까지 추가하는거를 다 신경쓰시고..! 🙌🙌

2023-02-20 19:02 UTC, fly1chop commented on src/components/layout/layout.tsx
> +  max-height: ${({ SIZE }) => SIZE.height};
이것도 앞서 COLORS와 같이 그대로 가져와서 사용하셔도 될것같아요~~

2023-02-20 19:02 UTC, fly1chop commented on src/styles/global.tsx
> -        font-size: 62.5%;
나중에 반응형을 고려하여 픽셀 대신 rem으로 사용하면 좋을것 같아 기본 루트 폰트 사이즈를 62.5%로 하고, 1rem = 10px로 생각하시고 사용하면됩니다..! 

제가 globalStyles PR에 언급했어야되는데 죄송합니다 ㅠㅠ

2023-02-21 02:31 UTC, Kal-MH commented on src/components/home-address/Header.tsx
> +  background-color: ${({ colors }) => colors.backgroundAccent};
음? 반영했는데 안 들어갔군요? 이상하네요...:)?

2023-02-21 02:32 UTC, Kal-MH commented on src/components/home-address/Main.tsx
> +const MAIN_TEXT = "만날 사람 주소를 추가해주세요";
그 main에서만 쓰이는 문구라 전역으로 관리하는 것보다 가까운 곳에서 관리하는 게 어떨까 생각했습니다. 혹시 다른 컴포넌트에서 쓰이는 부분이 있을까요?

2023-02-21 02:33 UTC, Kal-MH commented on src/components/layout/layout.tsx
> +  max-height: ${({ SIZE }) => SIZE.height};
이것도 반영이 안됐군요... 나 뭐 한 거지..?

2023-02-21 02:35 UTC, Kal-MH commented on src/styles/global.tsx
> -        font-size: 62.5%;
그, 제가 반응형 했던 부분에서 global.tsx를 합치니까 레이아웃이 깨지는 부분이 있더라구요 아무래도 global.tsx 원본 부분을 사용하신 게 편하신가요?

2023-02-21 08:24 UTC, fly1chop approved these changes
수고하셨습니다~~

2023-02-21 08:30 UTC, merged