Feature/place list api
prgrms-web-devcourse/Team-PODO-ODEEGO-FE pull request #90
Opened 2023-03-08 17:30 UTC by Kal-MH

## 이슈번호
[#88]
## 1. 작업내용

1. 디자인 수정
2. API 루트 변경
  - api routes를 활용해서 바꿨습니다,
3. 맵페이지와 싱크 맞추기
4. lazyloading 적용
![화면 캡처 2023-03-08 235642](https://user-images.githubusercontent.com/59648372/223786136-f3b33208-f5c2-47c3-bebb-adbb66d1268a.png)

## 2. 작업 하면서 겪은 이슈

- 백엔드에서 가져오는 이미지 url에 대해서 403이나, ERR_CERT_COMMON_NAME_INVALID 에러가 발생합니다.
  이미지를 제공해주는 서버의 보안정책 때문이 아닌가 판단해서 일단, 오류가 나는 이미지 컨테이너는 제외시키는 방향으로 구현했는데, 더 좋은 방법이 있을까요

## 3. PR 포인트

- defaultImage가 추가로 들어갈 예정입니다. (아직 없어용)

2023-03-09 07:49 UTC, fly1chop requested changes
수고하셨습니다~ 리뷰 확인해주세용~

2023-03-09 07:49 UTC, fly1chop commented on src/components/place/place-image.tsx
> +          onError={handleImageError}
P1;
`draggable={false}` 추가하면 좋을것같아요~

2023-03-09 07:49 UTC, fly1chop commented on src/components/place/place-input.tsx
>          }}
P3;
디자인에서도 이 부분은 input의 역할이 없고 그냥 헤더 요소라고 생각해도될것같은데요. 그래서 mui의 TextField 컴포넌트를 사용하는것보다 그냥 `<div><span>{value}</span></div>`로 해서 styled 컴포넌트로 구현하면 어떨까요?

2023-03-09 07:49 UTC, fly1chop commented on src/components/place/place.tsx
>          </IconsContainer>
P1;
공유 버튼을 mui `IconButton` 컴포넌트 사용하면 좋을 것 같아요~

2023-03-09 07:49 UTC, fly1chop commented on src/hooks/use-intersection-observer.ts
> +const useIntersectionObserver = ({
Ask;
혹시 이거 어디서 사용하고 있는건가요?

2023-03-09 07:49 UTC, fly1chop commented on src/hooks/use-lazyload-image.ts
> +const useLazyLoadImage = (lazy = false) => {
Ask;
와우 이거 다른 프로젝트에서 적용하게 참고해야겠어요 ㅎㅎ 근데 혹시 별도로 `lazy` 프롭스를 받아서 사용하는 이유가 있나요? 제가 생각했던거는 `useLazyLoadImage`를 사용하겠다 하면 매번 `lazy=true` 아닐까해서요 ^^;;

2023-03-09 07:49 UTC, fly1chop commented on src/pages/api/v1/places/index.ts
> +          .json({ message: ERROR_INTERNAL_SERVER_500, status: 500 });
P5;
이 부분 나중에 재관님 커스텀 에러 상수 사용해서 리팩토링 하면 좋을것 같아요~

2023-03-09 08:10 UTC, Kal-MH commented on src/components/place/place-input.tsx
>          }}
아, 사실 승환님 처음 디자인을 그대로 가져다 썼기 때문에 변경하지 않았어요.
refactor로 넘길까요...? 아이콘, 보더 다시 맞추기 너무 귀찮.... ㅠ

2023-03-09 08:10 UTC, Kal-MH commented on src/hooks/use-intersection-observer.ts
> +const useIntersectionObserver = ({
이거는 무한스크롤을 대비해서 미리 넣어둔 파일입니다~

2023-03-09 08:12 UTC, Kal-MH commented on src/components/place/place.tsx
>          </IconsContainer>
아, 여기가 원해 Bookmark랑 Share 버튼이랑 같이 있어서 div가 있는데요 지금은 빠져서 div도 필요없겠네요

2023-03-09 08:14 UTC, Kal-MH commented on src/hooks/use-lazyload-image.ts
> +const useLazyLoadImage = (lazy = false) => {
음,
일단은 저희 데브코스를 참고했고요
언제나 lazy를 사용하는 게 아닌 런타임 중간에 lazy를 멈춰야 하는 모든 경우를 생각해서 lazy 여부를 넣어두는 건 어떤가 해서 같이 포함시켰습니다.
확장성 아닌 확장성을 생각했어요.ㅎㅎ

2023-03-09 08:14 UTC, Kal-MH commented on src/pages/api/v1/places/index.ts
> +          .json({ message: ERROR_INTERNAL_SERVER_500, status: 500 });
넵, 저도 싱크 맞추면서 수정해보면 좋을 거 같습니다~

2023-03-09 08:21 UTC, Kal-MH commented on src/components/place/place-image.tsx
> +          onError={handleImageError}
main 컨테이너에 user-select: none을 넣어놨는데, 이미지에도 따로 설정해줘야 하나요:)?

2023-03-10 09:21 UTC, fly1chop approved these changes

2023-03-10 09:46 UTC, merged